Django/10-18/01-django-modelform/articles/urls.py
# URL설정을 app 단위로!
from django.urls import path 
from . import views

app_name = 'articles'

urlpatterns = [
  # http://127.0.0.1:8000/articles/
  path('', views.index, name='index'),
  # http://127.0.0.1:8000/articles/new/
  # path('new/', views.new, name='new'),
  # http://127.0.0.1:8000/articles/create/
  path('create/', views.create, name='create'),
  # http://127.0.0.1:8000/articles/1/ : 1번글
  # http://127.0.0.1:8000/articles/3/ : 3번글
  path('<int:pk>/', views.detail, name='detail'),
  # http://127.0.0.1:8000/articles/1/update/ : 1번글 수정
  # http://127.0.0.1:8000/articles/3/update/ : 3번글 수정
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/comments/', views.comment_create, name='comment_create'),
  path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

Django/10-18/01-django-modelform/articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models

# Create your models here.
"""
게시판 기능 
- 제목(20글자이내)
- 내용(긴 글)
- 글 작성시간/수정시간(자동으로 기록, 날짜/시간)
"""
# 1. 모델 설계 (DB 스키마 설계)
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

Django/10-18/01-django-modelform/articles/views.py
from xml.etree.ElementTree import Comment
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Article
from .forms import ArticleForm, CommentForm

# Create your views here.

# 요청 정보를 받아서..
def index(request):
    # 게시글을 가져와서..
    articles = Article.objects.order_by('-pk')
    # Template에 전달한다. 
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

# def new(request):
#     article_form = ArticleForm()
#     context = {
#         'article_form': article_form
#     }
#     return render(request, 'articles/new.html', context=context)

@login_required
def create(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            article_form.save()
            messages.success(request, '글 작성이 완료되었습니다.')
            return redirect('articles:index')
    else: 
        article_form = ArticleForm()
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context=context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


@login_required
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        # POST : input 값 가져와서, 검증하고, DB에 저장
        article_form = ArticleForm(request.POST, request.FILES, instance=article)
        if article_form.is_valid():
            # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
            article_form.save()
            messages.success(request, '글이 수정되었습니다.')
            return redirect('articles:detail', article.pk)
        # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        article_form = ArticleForm(instance=article)
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context)

def comment_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.save()
    return redirect('articles:detail', article.pk)

def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', article_pk)

Django/10-18/01-django-modelform/articles/templates/articles/detail.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block body %}
<h1>{{ article.pk }}번 게시글</h1>
<p>
  {{ article.created_at|date:"SHORT_DATETIME_FORMAT" }} | {{
  article.updated_at|date:"y-m-d D" }}
</p>
<p>{{ article.content }}</p>
{% if article.image %}
<img
  src="{{ article.image.url }}"
  alt="{{ article.image }}"
  width="400"
  height="300"
/>
{% endif %}
<a href="{% url 'articles:update' article.pk %}">수정하기</a>
<h4 class="my-3">댓글</h4>
<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
  {% csrf_token %} {% bootstrap_form comment_form layout='inline'%} {%
  bootstrap_button button_type="submit" content="OK" %}
</form>
<hr/>
<h4>댓글 목록</h4>
<ul>
  {% for comment in comments %}
  <li>{{ comment.content }}</li>
  <form
    action="{% url 'articles:comments_delete' article.pk comment.pk %}"
    method="POST"
  >
    {% csrf_token %}
    <input type="submit" value="DELETE" />
  </form>
  {% endfor %}
</ul>
<hr />
{% empty %}
<p>댓글이 없어요..</p>
{% endfor %}

Django/10-18/01-django-modelform/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %}
<h1> 글쓰기 </h1>
{% else %}
<h1> 수정하기 </h1>
{% endif %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form article_form %}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}

Django/10-18/01-django-modelform/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %} 
<h1>이미지</h1>
{% if request.user.is_authenticated %}
    <a class="btn btn-primary my-3 float-right" href="{% url 'articles:create' %}">글 쓰기</a>
{% endif %}

<div class="row">
  {% for article in articles %}
  <div class="col-4 my-3">
    <div class="card">
      {% if article.image %}
        <img src="{{ article.image.url }}" class="card-img-top" alt="...">
      {% else %}
        <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="card-img-top">
      {% endif %}
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-outline-primary my-3">복습하기</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}