Django/10-12/pjt/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    # 아래 주소에 들어오면 어떤 화면을 보여줄지
    # 생각하면서 path 를 작성 ...
    # http://127.0.0.1:8000/articles/
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

Django/10-12/pjt/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class User(models.Model):
    username = models.CharField(max_length=20)
    email = models.TextField()
    password1 = models.CharField(max_length=20)
    password2 = models.CharField(max_length=20)

Django/10-12/pjt/articles/forms.py
from django import forms
from .models import User
from .models import Article
from django.contrib.auth.forms import UserCreationForm

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'

class UserForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        models = User
        fields = UserCreationForm.Meta.fields

Django/10-12/pjt/articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm
from .models import Article

# Create your views here.

# 요청 정보를 받아서..
def index(request):
    articles = Article.objects.order_by("-pk")
    # template 에 뿌려준다
    context = {"articles": articles}
    return render(request, "articles/index.html", context)


def create(request):
    if request.method == "POST":
        # DB에 저장하는 로직
        article_form = ArticleForm(request.POST)
        if article_form.is_valid():
            article_form.save()
            return redirect("articles:index")
    else:
        article_form = ArticleForm()
    context = {"article_form": article_form}
    return render(request, "articles/new.html", context=context)


def detail(request, pk):
    # 특정 글을 가져온다.
    #                        .get(모델칼럼명=urls.py에서 쓴 인자)
    article = Article.objects.get(pk=pk)
    # template 에 객체 전달
    context = {"article": article}
    return render(request, "articles/detail.html", context)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        # POST : input 가져와서 검증하고 DB 에 저장
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            # 유효성 검사 통과하면 저장후 상세보기 페이지로
            article_form.save()
            return redirect("articles:detail", article.pk)
        # 유효성 검사 통과 못하면 => 오류메세지
    else:
        # GET 처리 : Form 을 제공
        article_form = ArticleForm(instance=article)
    context = {"article_form": article_form}
    return render(request, "articles/update.html", context)


def delete(request, pk):
    Article.objects.get(pk=pk).delete()
    return redirect("articles:index")

Django/10-12/pjt/articles/templates/articles/detail.html
{% extends 'base.html' %} {% block content %}

<h1>{{ article.pk }}번 게시글</h1>
<h3>{{ article.title }}</h3>
<p>{{ article.created_at }} | {{ article.updated_at }}</p>
<p>{{ article.content }}</p>
<a href="{% url 'articles:update' article.pk %}">수정하기</a>
<a href="{% url 'articles:delete' article.pk %}">삭제하기</a>

{% endblock %}

Django/10-12/pjt/articles/templates/articles/index.html
{% extends 'base.html' %} {% block content %} {% load static %}

<h1>안녕!</h1>
<img src="{% static '.jpg' %}" alt="img" />

<a href="{% url 'articles:create' %}">새글쓰기</a>
{% for article in articles %}
<h3>
  <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
</h3>
<p>{{ article.created_at }} | {{ article.updated_at }}</p>
<hr />
{% endfor %} {% endblock %}

Django/10-12/pjt/articles/templates/articles/new.html
{% extends 'base.html' %} {% block content %} {% load django_bootstrap5 %} 
{% bootstrap_css %} {% bootstrap_javascript %}

<h1>글쓰기</h1>
<form action="" method="POST">
  {% csrf_token %} {% bootstrap_form article_form %} 
  {% bootstrap_button content="글쓰기" button_type="submit"%}
</form>

{% endblock %}