Django/10-07 프로젝트/movie/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("articles/", views.articles, name="articles"),
]

Django/10-07 프로젝트/movie/movie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
]

Django/10-07 프로젝트/movie/articles/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    movie_name = models.TextField(null=True)
    grade = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)], help_text="0~5")
    created_at = models.DateTimeField(default=timezone.now)
    # auto_now_add로 속성 정의했더니 django.core.exceptions.FieldError: 'created_at' cannot be specified for Review model form as it is a non-editable field  라는 오류가 떠서
    # default=timezone.now으로 임시로 적어둠.
    updated_at = models.DateTimeField(default=timezone.now)

    

Django/10-07 프로젝트/movie/articles/forms.py
from django import forms
from .models import User

class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['user','email','password1','password2']
        


        

Django/10-07 프로젝트/movie/articles/views.py
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm

# Create your views here.


def index(request):
    articles = Review.objects.order_by("-pk")
    context = {"articles": articles}
    return render(request, "articles/index.html", context)


# def new(request):
#     article_form = ReviewForm()
#     context = {
#         'review_form' : article_form
#     }
#     return render(request, 'articles/new.html',context=context)


def create(request):
    if request.method == "POST":
        # title = request.POST.get('title')
        # content = request.POST.get('content')
        # movie_name = request.POST.get('movie_name')
        # grade = request.POST.get('grade')
        # created_at = request.POST.get('created_at')
        # updated_at = request.POST.get('updated_at')
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect("articles:index")
    else:
        article_form = ReviewForm()
    context = {"review_form": article_form}
    return render(request, "articles/new.html", context=context)
    # Review.objects.create(title=title, content=content, movie_name=movie_name, grade=grade, created_at=created_at, updated_at=updated_at)


def detail(request, pk):
    article = Review.objects.get(pk=pk)
    context = {"article": article}
    return render(request, "articles/detail.html", context)


def update(request, pk):
    article = Review.objects.get(pk=pk)
    if request.method == "POST":
        review_form = ReviewForm(request.POST, instance=article)
        if review_form.is_valid():
            review_form.save()
        return redirect("articles:detail", article.pk)
    else:
        review_form = ReviewForm(instance=article)

    context = {"review_form": review_form}
    return render(request, "articles/update.html", context)


def delete(request, pk):
    Review.objects.get(pk=pk).delete()
    return redirect("articles:index")


def articles(request):
    articles = Review.objects.order_by("-pk")
    context = {"articles": articles}
    return render(request, "articles/articles.html", context)

Django/10-07 프로젝트/movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="css/style.css"/>
    <title>MOVIE</title>
  </head>
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />

  <body>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel = 'stylesheet' href="{% static 'css/style.css' %}">
    <title> <img src = "{% static 'image/1.jpg' %}" alt="MOVIE">MOVIE</title>
      <nav class="navbar navbar-expand-lg" style="background-color: gold">
        <div class="container-fluid">
        <a class="navbar-brand" aria-current="page" href="{% url 'articles:articles' %}"
        >MOVIE</a>
        
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'articles:index' %}"
                >리뷰 목록</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'articles:create' %}">리뷰 작성</a>
            </li>

          </form>
        </div>
      </div>
    </nav>
  </nav>
</div>
    {% block content %}{% endblock %}


    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
  </body>
</html>